---
- name: Initialize Ubuntu instances for CIS compliance
  hosts: ubuntu
  become: yes
  vars:
    # แนะนำให้กำหนดค่า ubuntu_password ผ่านทาง Semaphore Extra Variables จะปลอดภัยที่สุด
    # ตัวอย่าง: {"ubuntu_password": "MySuperSecretPassword123!"}
    ubuntu_password: "ChangeMe123!"
  
  tasks:
    - name: Check if ubuntu user has a password
      ansible.builtin.shell: "awk -F: '$1==\"ubuntu\" {print $2}' /etc/shadow"
      register: shadow_pass
      changed_when: false

    - name: Set password for ubuntu user if not set (Required for CIS sudo rules)
      ansible.builtin.shell: "echo 'ubuntu:{{ ubuntu_password }}' | chpasswd"
      no_log: true
      when: shadow_pass.stdout == '!' or shadow_pass.stdout == '*'
